/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp demo.xml -i mytype.h -a MyTypeAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MYTYPEADAPTOR_H
#define MYTYPEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "mytype.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface a.b.c.d
 */
class DAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "a.b.c.d")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"a.b.c.d\">\n"
"    <property access=\"readwrite\" type=\"s\" name=\"nickname\"/>\n"
"    <signal name=\"sayHello\"/>\n"
"    <method name=\"helloJerry\">\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"helloTom\">\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"    </method>\n"
"    <method name=\"hello\">\n"
"      <arg direction=\"in\" type=\"a(i)\" name=\"MyType\"/>\n"
"      <annotation value=\"MyType\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DAdaptor(QObject *parent);
    virtual ~DAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString nickname READ nickname WRITE setNickname)
    QString nickname() const;
    void setNickname(const QString &value);

public Q_SLOTS: // METHODS
    void hello(MyType qqq);
    QDBusVariant helloJerry(const QString &name);
    QDBusVariant helloTom();
Q_SIGNALS: // SIGNALS
    void sayHello();
};

#endif
